name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    env:
      PYTHON_VERSION: 3.9
      UV_VERSION: 0.7.9

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Lint
        run: uv run black --check .

      - name: Build
        run: uv build

      - name: Test
        run: uv run pytest

  test:
    name: Test
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13" ]
    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"


      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Build
        run: uv build

      - name: Test
        run: uv run pytest
