name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Lint
        run: poetry run black --check .

      - name: Build
        run: poetry build

      # the `coverage xml -i` command is needed to re-write the
      # coverage report with relative paths
      - name: Test
        run: |
          poetry run pytest --cov src --cov-report xml tests
          poetry run coverage xml -i

  test:
    name: Test
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        poetry-version: ["1.8.2"]
        include:
          - python-version: "3.7"
            poetry-version: "1.5.1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "${{ matrix.poetry-version }}"

      - name: Install dependencies
        run: poetry install

      - name: Build
        run: poetry build

      - name: Test
        run: poetry run tox
