name: Pull request checks

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  check-title:
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
    name: Check title
    runs-on: ubuntu-20.04

    steps:
      - uses: naveenk1223/action-pr-title@v1.0.0
        with:
          regex: '^(chore|demo|deprecate|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?: .+$'
          max_length: 60
